# Generated by rpcgen.py at Tue Nov 29 11:01:00 2005

# Need to import flavors mentioned in secinfo4
from rpc import RPCSEC_GSS

FALSE = 0
TRUE = 1

AGPROC_VGW_CMD = 1
AGPROC_VGW_VERS = 1
AGPROC_VGW_PROG = 0x20000021
