# Generated by rpcgen.py at Tue Nov 29 11:01:00 2005

from ag_vgwconstants import *
from ag_vgwpacker import *
try:
    # Assume that the python xdrlib comes first on the PYTHONPATH
    from xdrlib import Error as XDRError
except ImportError:
    # Never mind. I will use the pynfs one.
    from xdrlib import XDRError
    
import rpc

class BadDiscriminant(rpc.RPCException):
    def __init__(self, value, klass):
        self.value = value
        self.klass = klass

    def __str__(self):
        return "Bad Discriminant %s in %s" % (self.value, self.klass)

class tgVform:
    # XDR definition:
    # struct tgVform {
    #     char head[60];
    #     long tv_sec;
    #     long tv_usec;
    #     unsigned_short data<>;
    # };
    def __init__(self, head=None, tv_sec=None, tv_usec=None, data=None):
        self.head = head
        self.tv_sec = tv_sec
        self.tv_usec = tv_usec
        self.data = data

    def __repr__(self):
        s = " head=%s tv_sec=%s tv_usec=%s data=%s" % (str(self.head), str(self.tv_sec), str(self.tv_usec), str(self.data))
        if len(s) > 70: s = s[:70] + "..."
        return "<tgVform:%s>" % s

