void SH_MsgLog(char*, char*);
double SH_ToolRAtoDeg(char*);
double SH_ToolDECtoDeg(char*);
double SH_ToolMintoDeg(char*);
double SH_ToolChartoDbl(char*);
int SH_ToolChartoInt(char*);
static int SH_Func(struct SH_List*, struct SH_List*);
void SH_CalcPreference(int);
int SH_ReadCfgInt(char*, int*);
int SH_ReadCfgDbl(char*, double*);
