# Generated by rpcgen.py at Tue Sep 16 18:36:06 2008

# Need to import flavors mentioned in secinfo4
from rpc import RPCSEC_GSS

FALSE = 0
TRUE = 1

DAQTK_DAT_SND_MEM = 1
DAQTK_DAT_SND_MEM_VERS = 1
DAQTK_DAT_SND_MEM_PROG = 0x21010951L
